### ISSUE TITLE
请问一下，这个插件的具体使用方法和功能是什么，因为我只做uniapp小程序的开发，这个是在vscode调试APP开发时打开微信开发者工具这样的吗？方便调试？

### ISSUE THREAD

**Issue by Vogadero** [hb0730/vscode-uniapp-run#23]
因为我只做uniapp小程序的开发，这个是在vscode调试APP开发时打开微信开发者工具或者HBuildX工具这样的吗？方便调试？

**Comment by hb0730** [comment]
只支持小程序、暂不支持app的相关开发

**Comment by Vogadero** [comment]
> 只支持小程序、暂不支持app的相关开发

所以我想问问这个到底是怎么运行的，感觉可以用，但是不知道如何使用，使用文档有点简略，把HBuildx创建的小程序导入vscode运行吗？

**Comment by hb0730** [comment]
适用于HBuilder创建的uniapp项目、

**Comment by Vogadero** [comment]
> 适用于HBuilder创建的uniapp项目、

那应该怎么使用呀？我HBuilder创建的uniapp项目，package.json里都没有任何运行命令的？我该怎么看到你这个插件运行起来了，或者怎么运行你这个插件。完全没头绪，真心求请教

**Comment by hb0730** [comment]
1. vscode 商店安装`hb0730.uniapp-run`
2. 配置HBuilder安装路径
3. 配置`.vscode/launch.json`
4. 启动vscode的debug

**Comment by Vogadero** [comment]
.vscode/launch.json这个文件在哪里可以找到，HBuilder创建的uniapp项目没有这个文件夹😂

**Comment by Vogadero** [comment]
> 4\. 启动vscode的debug
第四步：启动vscode的debug。这个插件是专门用来debug的吗？？？

**Comment by hb0730** [comment]
> .vscode/launch.json这个文件在哪里可以找到，HBuilder创建的uniapp项目没有这个文件夹😂

专门使用vscode进行编码的，项目跟目录下创建`.vscode/launch.json`，

**Comment by hb0730** [comment]
> > 4. 启动vscode的debug
> > 第四步：启动vscode的debug。这个插件是专门用来debug的吗？？？

vscode的运行与调试

**Comment by Vogadero** [comment]
感谢大哥，等我测试一下这个神器，去市场给你好评

**Comment by hb0730** [comment]
**这不支持app调试与开发**

**Comment by Vogadero** [comment]
> **这不支持app调试与开发**

那更好，我就是写小程序的，我还没试过运行与调试功能，改天摸索摸索🤣
