### ISSUE TITLE
能否添加下 自定义编译

### ISSUE THREAD

**Issue by yanwuguangjun** [hb0730/vscode-uniapp-run#35]
能不能添加 支持 自定义编译方式
如  [https://uniapp.dcloud.net.cn/collocation/package.html#package-json](https://uniapp.dcloud.net.cn/collocation/package.html#package-json)

**Comment by hb0730** [comment]
> UNI_PLATFORM仅支持填写uni-app默认支持的基准平台，目前仅限如下枚举值：h5、mp-weixin、mp-alipay、mp-baidu、mp-toutiao、mp-qq

关于 `基准`已经全部支持,所以感觉没有什么特别场景进行单独支持,或许需要的是启动多个不同`UNI_PLATFORM`的`vscode-uniapp-run`

**Comment by supeng844** [comment]
package.json增加自定义条件编译，怎么配置打包呢
