### ISSUE TITLE
关于开发微信小程序发布相关

### ISSUE THREAD

**Issue by binscor** [hb0730/vscode-uniapp-run#36]
你好，我目前编码结束之后，还需要打开hbuiderx之后去发布，我想问一下目前是否支持hbuildx里面的发布功能呢，或者后续是否有相关的开发计划啊
![image](https://github.com/hb0730/vscode-uniapp-run/assets/37325821/7d2aa187-f415-4f02-8b6e-5affc6ec26f6)

**Comment by hb0730** [comment]
我觉得可以直接使用**微信开发者工具**直接发布 ^ _ ^

**Comment by binscor** [comment]
其实在vscode中开发的时候，默认打包的话应该是以dev环境打包到微信开发者工具的，但是发布的话打包的方式应该是正式环境打包到微信开发者工具，然后再去发布

**Comment by hb0730** [comment]
> 其实在vscode中开发的时候，默认打包的话应该是以dev环境打包到微信开发者工具的，但是发布的话打包的方式应该是正式环境打包到微信开发者工具，然后再去发布

目前来说硬编码为`development`,如果是发布则可能是`production`环境，这个得研究研究，不一定能够实现

**Comment by binscor** [comment]
![image](https://github.com/hb0730/vscode-uniapp-run/assets/37325821/5fe62f7b-9124-4b21-baf7-0c6f04a53385)
这是我刚刚调查出来的结果，但是我对vscode插件的开发不太了解
这个是官方的文档：https://hx.dcloud.net.cn/cli/publish-mp-weixin?id=cmd

**Comment by binscor** [comment]
我自己的想法的话大概就是这条命令执行成功之后，可以根据配置来决定发布之后是否自动启动微信开发者工具，打开这个打包的项目

**Comment by hb0730** [comment]
> ![image](https://private-user-images.githubusercontent.com/37325821/322679492-5fe62f7b-9124-4b21-baf7-0c6f04a53385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzQ0ODYsIm5iZiI6MTcxMzIzNDE4NiwicGF0aCI6Ii8zNzMyNTgyMS8zMjI2Nzk0OTItNWZlNjJmN2ItOTEyNC00YjIxLWJhZjctMGM2ZjA0YTUzMzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAyMjMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMzRiMTYyMjQzMjkwNjNhNGMxMGY3OThhYzBiNDIxNDU5NGY5NjZjMThlZWJkM2E3MzJlY2FhNzMzMDBmOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zsjNurgA_HVlK2xnd04ptPJDciR6iOWmQFxV8uQyPPM) 这是我刚刚调查出来的结果，但是我对vscode插件的开发不太了解 这个是官方的文档：https://hx.dcloud.net.cn/cli/publish-mp-weixin?id=cmd

感谢提供相关参考文档，当我空闲下来会研究的，如果有兴趣也欢迎进行PR

**Comment by hb0730** [comment]
hei,请将插件更新为最新版本，如有问题请提[issues](https://github.com/hb0730/vscode-uniapp-run/issues) , 相关提交 31dd1220f73d90d7a85c5e42b4238397267524d7

**Comment by binscor** [comment]
非常感谢！
