### ISSUE TITLE
0.0.8版本windows环境中uniapp发布的错误

### ISSUE THREAD

**Issue by binscor** [hb0730/vscode-uniapp-run#37]
首先很感谢上次我提出的功能这么快就加上了!
文件这个位置的代码：**E:\BrowerDownload\vscode-uniapp-run-main\src\commands\publish.ts:50**
windows环境下，获取项目路径似乎不太对
![image](https://github.com/hb0730/vscode-uniapp-run/assets/37325821/1f4dc801-c879-456e-86db-f4b57aa65925)
如果我不配置上图中的这个src的路径的话，currentWorkspace.uri.path获取到的路径是错误的，windows里面绝对路径只能以盘符开头
![image](https://github.com/hb0730/vscode-uniapp-run/assets/37325821/81fa1ba8-8087-4566-9089-3ae146edf1b3)
然后打包就会失败

另外就是整个打包结束没有提示，也无法自动打开调起开发工具，即使是openDevTool设置为true的情况下

**Comment by hb0730** [comment]
<img width="1424" alt="image" src="https://github.com/hb0730/vscode-uniapp-run/assets/33956166/a62ac7d1-455b-475f-b642-d321d8a42e07">


请离线安装试一试https://zh-cn.tempdrive.zip/s/31bb262a

**Comment by hb0730** [comment]
现在日志应该在`output/输出` 里的`uniapp-run`进行查看

**Comment by binscor** [comment]
目前这个已经过期了，下载不了了

**Comment by hb0730** [comment]
> 目前这个已经过期了，下载不了了

https://zh-cn.tempdrive.zip/s/e4df0928

**Comment by binscor** [comment]
![image](https://github.com/hb0730/vscode-uniapp-run/assets/37325821/5ef50437-c1e0-472c-a0fe-2d86af1e90b6)
开发者工具安装路径中有个空格，导致开发者工具启动不了

**Comment by hb0730** [comment]
> ![image](https://private-user-images.githubusercontent.com/37325821/324157840-5ef50437-c1e0-472c-a0fe-2d86af1e90b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTQwMDAsIm5iZiI6MTcxMzU5MzcwMCwicGF0aCI6Ii8zNzMyNTgyMS8zMjQxNTc4NDAtNWVmNTA0MzctYzFlMC00NzJjLWEwZmUtMmQ4NmFmMWU5MGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA2MTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMDZjMjViOTgxZjRiZTcxMWRjYjAxOTZhNzNlNzBlMDk0MzQyN2IzZWM3YTUwY2Y5MjY2OWZiYjZmNGEwNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JW_mQSrdfsEs0iJ1pwK8foL4GdE8emIDnU5bUy5yH4c) 开发者工具安装路径中有个空格，导致开发者工具启动不了

https://zh-cn.tempdrive.zip/s/ba11d54e  😂万万没想到

**Comment by binscor** [comment]
现在都OK了，windows平台就这样的，很多东西不太规范

**Comment by hb0730** [comment]
OK，感谢参与调试
