### ISSUE TITLE
使用该插件编译出来的h5文件不完整

### ISSUE THREAD

**Issue by Whuihuan** [hb0730/vscode-uniapp-run#40]
![image](https://github.com/hb0730/vscode-uniapp-run/assets/6679148/a70b9557-8290-46bc-8f2d-d8300736545f)
这是hbuilderx编译出来的
![image](https://github.com/hb0730/vscode-uniapp-run/assets/6679148/c580882f-52e5-42c9-893c-390bef03f3f6)
这是插件编译出来的
![image](https://github.com/hb0730/vscode-uniapp-run/assets/6679148/d7a9a12c-8b4b-4beb-98d8-251b33c28636)
这是配置

**Comment by hb0730** [comment]
请问有最小可复现的demo么

**Comment by Whuihuan** [comment]
> 请问有最小可复现的demo么

我弄了个简单的uniapp，好像又可以。只不过出问题的是公司的项目，那就没办法了，只能用hbuilderx手动发行了

**Comment by hb0730** [comment]
那就不好意思了，该插件只验证过编译小程序的，编译H5并未验证过，提供能力的是
```
vue2:`${HBuilderPath}/Contents/HBuilder/plugins/uniapp-cli/bin/uniapp-cli.js` vue3:`${HBuilderPath}/Contents/HBuilder/plugins/uniapp-cli-vite/bin/uni.js
```
如果无法提供复现demo，可无法确认编译命令是否与`hbuilderx`编译命令是否一致
