### ISSUE TITLE
uniapp发布 点击无效

### ISSUE THREAD

**Issue by P-Mz** [hb0730/vscode-uniapp-run#44]
vscode版本信息: 

版本: 1.89.1 (user setup)
提交: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
日期: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.17763

------------------------------
HBuilderX版本: 4.24

------------------------------
![image](https://github.com/user-attachments/assets/b71cdbf4-6907-4028-b135-bb01a4bcea64)

点击后有看到有这个进程但是没有如何反应
![image](https://github.com/user-attachments/assets/a39e7b14-8f24-4a7e-b279-79b4a03cd43a)

**Comment by hb0730** [comment]
<img width="1410" alt="image" src="https://github.com/user-attachments/assets/6e78c63d-cc64-4728-ada7-112250f561eb">
请检查相关输出日志，`uniapp 发布` 也只是进行 `build 命令`

**Comment by hb0730** [comment]
uniapp 构建 启动的是 vscode debug模式
uniapp 发布 启动的是 命令 模式

或许可能将其保持一致，比较好

**Comment by P-Mz** [comment]
> uniapp 构建 启动的是 vscode debug模式 uniapp 发布 启动的是 命令 模式
> 
> 或许可能将其保持一致，比较好

找到输出的内容了, 应该是HBuilderX问题
ERROR  Error: No module factory available for dependency type: CssDependency
图片附不上来

**Comment by hb0730** [comment]
找到问题就好，👌

**Comment by supeng844** [comment]
发布不需要登录 dcloud 要互联网吧
