### ISSUE TITLE
希望能指导一下

### ISSUE THREAD

**Issue by Zhengjincheng33** [hb0730/vscode-uniapp-run#45]
我左边工作区里面很多个项目，我要怎么去运行， 现在运行不了，只能单个文件夹打开的时候进行调试模式运行，希望能有办法

**Comment by hb0730** [comment]
<img width="916" alt="image" src="https://github.com/user-attachments/assets/fa946033-3366-4a43-b5a9-b6b55532fd9b">

工作区目录中的`launch.json`可以新增对应的`src`需要运行的项目目
