### ISSUE TITLE
配置内容h5 提示错误

### ISSUE THREAD

**Issue by wzc-ST** [hb0730/vscode-uniapp-run#5]
![1690941051867](https://github.com/hb0730/vscode-uniapp-run/assets/51228283/ad33caf4-a868-4acc-8a1f-6e9812cd04d2)

**Comment by wzc-ST** [comment]
但是可以正常运行，只是提示Value is not accepted.

**Comment by hb0730** [comment]
> 但是可以正常运行，只是提示Value is not accepted.

1. 正常运行, 这只是使用的uniapp的cli,基本上只要uniapp支持的应该都是没有问题的
2. 只是提示Value is not accepted. 因为原先设计的只是小程序相关的采用vscode编码，采用uniapp进行编译，所以只声明小程序相关的

**Comment by wzc-ST** [comment]
你好，如果 uniapp 的 自定义编译平台配置 的需要怎么设置才能运行呢？
