### ISSUE TITLE
win没运行起来

### ISSUE THREAD

**Issue by ayuan-gy** [hb0730/vscode-uniapp-run#8]
![image](https://github.com/hb0730/vscode-uniapp-run/assets/82928935/e4e86c7f-a6e2-4f7b-9138-7a32ca31fb2b)

**Comment by hb0730** [comment]
我看hbuildx地址是hbuildx.exe、是否尝试过目录huildx

**Comment by supeng844** [comment]
可以Hbuilder可以运行项目，但是工具运行和打包都是提示 spawn 报错
